# Site settings
title: Faethon's quest to entrepreneurship
email: faethon.milikouris@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A few years ago I decided that one day i will build my own awesome company with an awesome service for awesome people. Im on a quest to learn us much as I can so i can accomplish that
baseurl: '/blog'
url: "https://faethonm.herokuapp.com/" # the base hostname & protocol for your site
twitter_username: faethonm
github_username:  faethonm

# Build settings
markdown: kramdown
